// user.interface.ts

// Generated by https://quicktype.io

export interface User {
  id: number;
  first_name: string;
  last_name: string;
  email: string;
  phone: string;
  location: string;
  state: boolean;
  /* createdAt:  string;
  updatedAt:  string; */
}
